input_dir: C:/Users/miles/Documents/Business/Personal Projects/DATA dump/Simulated Broker Dealer/2025-04-18
lake_root: C:/Users/miles/Documents/Business/Personal Projects/DATA dump/Reporting Service/lake
reports_dir: C:/Users/miles/Documents/Business/Personal Projects/DATA dump/Reporting Service/reports
run_id: 20250418_01

spark:
  extensions: "io.delta.sql.DeltaSparkSessionExtension"
  catalog: "org.apache.spark.sql.delta.catalog.DeltaCatalog"
  nativeio_disable: true
  winutils_path: "C:\\hadoop\\hadoop-3.3.6\\bin\\winutils.exe"

hadoop:
  version: "3.3.6"
  home_dir: "C:\\hadoop\\hadoop-3.3.6"
  winutils_path: "C:\\hadoop\\hadoop-3.3.6\\bin\\winutils.exe"
  nativeio_disable: true
